name: Pages

on:
  push:
    branches:
      - blog-source  # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Pandoc
        run: |
          curl -s -L https://github.com/jgm/pandoc/releases/download/2.9.2/pandoc-2.9.2-linux-amd64.tar.gz | tar xvzf - -C ${{ secrets.RUNNER_TOOL_CACHE }}/
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Clean NPM cache
        run: npm cache clean --force
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: |
          export PATH="$PATH:${{ secrets.RUNNER_TOOL_CACHE }}/pandoc-2.9.2/bin"
          npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./public
          external_repository: anyin233/anyin233.github.io
          publish_branch: master  # deploying branch
      - name: notify
        run: curl -s -0 /dev/null "https://api.day.app/${{ secrets.BARK_TOKEN }}/Git Pages Deploy/Deploy Finished"
